#!/bin/bash

function check_okay {
	if [ $? -ne 0 ]
	then
		exit 1
	fi
}


function do_one {
	cp $1 inlist
	check_okay
	rm -rf $2
	echo 'run' $1
	./rn1
	check_okay
  if [ ! -r $2 ]
  then
  	echo
  	echo "******************************************************************"
  	echo 'failed to create' $2 'when running' $1
  	echo "******************************************************************"
  	echo
  	exit 1
  fi
  echo
  echo 'finished' $1
  rm -rf $3
  mkdir $3
  mv LOGS/* $3
  echo
  echo '***'
  echo '***'
  echo '***'
  echo '***'
  echo '***'
  echo '***'
  echo
}


date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_start start.mod LOGS_start
do_one inlist_zams_to_rgb_tip end_agb.mod LOGS_to_end_agb
# do_one inlist_rgb_tip_to_hezams_template final.mod LOGS_to_wd
# do_one inlist_hezams_to_agb_template final.mod LOGS_to_wd

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished all inlists for 1M_pre_ms_to_wd'

